dist: xenial
language: python
cache: pip
services:
    - postgresql
python:
    - "3.7.3"
env:
  global:
    - DJANGO_SETTINGS_MODULE="project.settings"
  matrix:
    - DJANGO_VERSION=2.2 DB=postgres
before_script:
    - psql -c 'create database loan_db;' -U postgres
install:
    - if [[ $DB == postgres ]]; then pip install -q psycopg2-binary; fi
    - pip install pipenv --upgrade
    - pipenv sync -d
script:
    - black --check project/ api/
    - python manage.py migrate
    - python manage.py test
after_success:
    - codecov
deploy:
  provider: heroku
  api_key:
    secure: $KEY_HEROKU

