dist: xenial
language: python
cache: pip
services:
    - postgresql
python:
    - "3.7.3"
before_script:
    - psql -c "create database loan_db;" -U postgres
install:
    - pip install pipenv --upgrade
    - pipenv sync -d
script:
    - black --check project/ api/
    - python manage.py migrate
    - python manage.py test
    - coverage run --source="." manage.py test api
after_success:
    - codecov
